### ISSUE TITLE
Store the jar/md5 in a non-temp directory

### ISSUE THREAD

**Issue by jcoyne** [cbeer/fcrepo_wrapper#32]
So that I don't have to re-download ever time I reboot my machine.  Solr_wrapper already has this feature.

**Comment by cbeer** [comment]
Does creating a `~/.fcrepo_wrapper.yml` file with:

```
download_dir: /some/path
```

not address this?

**Comment by jcoyne** [comment]
possibly does. I want to take a look at how solr_wrapper is doing it.

**Comment by jcoyne** [comment]
https://github.com/cbeer/solr_wrapper/blob/master/lib/solr_wrapper/configuration.rb#L59-L65

**Comment by jcoyne** [comment]
Huh, I can't reproduce this now.  Unsure why I saw this.
